### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by horsaen** [horsaen/the-deftaeris-project#1]
- [x] Add logic that removes learn more from the general language sources site
- [ ] Add home button to resource page
- [ ] Add Bing search support ?
- [ ] Sitemap ? idk google's being dumb
